food_tracker/food/urls.py
from django.conf.urls import url

from .views import index, add_meal, delete_meal, update_meal, add_food, view_meal, login


urlpatterns = [
	url(r'^$', login, name='login'),
    url(r'^index$', index, name='index'),
    url(r'^add_meal$', add_meal, name='add-meal'),
    url(r'^view_meal/(?P<meal_id>\d+)$', view_meal, name='view-meal'),
    url(r'^add_food$', add_food, name='add-food'),
    url(r'^delete_meal/(?P<meal_id>\d+)$', delete_meal, name='delete-meal'),
    url(r'^update_meal/(?P<meal_id>\d+)$', update_meal, name='update-meal'),
]


food_tracker/food_tracker/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
	url(r'^', include(('food.urls','food'), namespace="food")),
	path('admin/', admin.site.urls),
	url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'), name='auth_login'),
	url(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page='food:login'), name='auth_logout'),
	url(r'^accounts/password/change$', auth_views.PasswordChangeView.as_view (template_name='password_change.html',success_url=reverse_lazy('food:login')),name='auth_password_change'),
]


food_tracker/food/models.py
from django.db import models

# Create your models here.

class Food(models.Model):
	name = models.CharField(verbose_name="Food Name", max_length=200)
	calories = models.FloatField(verbose_name="Calories (kcal)")
	total_fat = models.FloatField(verbose_name="Total Fat (g)")
	saturated_fat = models.FloatField(verbose_name="Saturated Fat (g)")
	cholesterol = models.FloatField(verbose_name="Cholesterol (mg)")
	sodium = models.FloatField(verbose_name="Sodium (mg)")
	total_carbohydrate = models.FloatField(verbose_name="Total Carbohydrate (g)")
	dietary_fibre = models.FloatField(verbose_name="Dietary Fibre (g)")
	sugar = models.FloatField(verbose_name="Sugar (g)")
	protein = models.FloatField(verbose_name="Protein (g)")

	def __str__(self):
		return "%s" % self.name


class Meal(models.Model):
	BREAKFAST = 1
	MORNING_SNACK = 2
	LUNCH = 3
	AFTERNOON_SNACK = 4
	DINNER = 5
	EVENING_SNACK = 6

	MEAL_TIME_TYPES = (
		(BREAKFAST, "Breakfast"),
		(MORNING_SNACK, "Morning Snack"),
		(LUNCH, "Lunch"),
		(AFTERNOON_SNACK, "Afternoon Snack"),
		(DINNER, "Dinner"),
		(EVENING_SNACK, "Evening Snack")
	)

	food = models.ForeignKey(Food, verbose_name="Food", on_delete = models.CASCADE)
	serving_size = models.IntegerField(verbose_name="Serving Size")
	meal_time = models.IntegerField(verbose_name="Meal Time", choices=MEAL_TIME_TYPES)


	def __str__(self):
		return "%s" % self.food

	def get_calories(self):
		return self.food.calories * self.serving_size

	def get_total_fat(self):
		return self.food.total_fat * self.serving_size

	def get_saturated_fat(self):
		return self.food.saturated_fat * self.serving_size

	def get_cholesterol(self):
		return self.food.cholesterol * self.serving_size

	def get_sodium(self):
		return self.food.sodium * self.serving_size 

	def get_total_carbohydrate(self):
		return self.food.total_carbohydrate * self.serving_size

	def get_dietary_fibre(self):
		return self.food.dietary_fibre * self.serving_size

	def get_sugar(self):
		return self.food.sugar * self.serving_size

	def get_protein(self):
		return self.food.protein * self.serving_size 

	def get_meal_time(self):
		meal_time_type = ["Breakfast", "Morning Snack", "Lunch", "Afternoon Snack", "Dinner", "Evening Snack"]
		return meal_time_type[self.meal_time-1]

food_tracker/food/forms.py
from django import forms
from .models import Meal, Food

class MealForm(forms.ModelForm):
	class Meta:
		model = Meal
		fields = "__all__"

class FoodForm(forms.ModelForm):
	class Meta:
		model = Food
		fields = "__all__"

food_tracker/food/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Food, Meal
from .forms import MealForm, FoodForm




def index(request):
	#template = 'home.html'
	template = 'list.html'
	meals = Meal.objects.all()
	context = {
		'meals': meals,
	}
	return render(request, template, context)
	#return HttpResponse("Hello World!")

def add_food(request):
	template = "add_food.html"

	if request.method == "POST":
		print("Posting")
		form = FoodForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse_lazy('food:index'))
		else:
			print("Invalid form")

	else:
		context = {
			'food_form': FoodForm(),
		}
	
	return render(request, template, context)

def add_meal(request):
	template = "add_meal.html"

	if request.method == "POST":
		form = MealForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse_lazy('food:index'))
	else:
		context = {
			'meal_form': MealForm(),
		}
	
	return render(request, template, context)

def view_meal(request, meal_id):
	template = "view_meal.html"
	meal = Meal.objects.get(id=int(meal_id))
	
	context = {
		'meal': meal
	}
	return render(request, template, context)


def delete_meal(request, meal_id):
	meal = Meal.objects.get(id=int(meal_id))
	meal.delete()
	return HttpResponseRedirect(reverse_lazy('food:index'))

def update_meal(request, meal_id):
	template = "update_meal.html"
	meal = Meal.objects.get(id=int(meal_id))

	if request.method == "POST":
		form = MealForm(request.POST, instance=meal)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse_lazy('food:index'))
	else:
		context = {
			'meal_form': MealForm(instance=meal),
		}
	return render(request, template, context)


def login(request):
	
	if request.user.is_authenticated:
		return HttpResponseRedirect(reverse_lazy('food:index'))
	else:
		return HttpResponseRedirect(reverse_lazy('auth_login'))

food_tracker/templates/add_food.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker - Add Food</h1>
		<a href="{% url 'food:index' %}" class="btn btn-info">Back</a><br />
		<form role="form" action="" method="POST">
		    {% csrf_token %}
			<table class="table table-dark table-bordered table-striped">
				<tbody>
					<tr>
						<th>Food</th>
						<th>{{ food_form.name }}</th>
					</tr>
					<tr>
						<th>Calories</th>
						<th>{{ food_form.calories }} kcal</th>
					</tr>
					<tr>
						<th>Total Fat</th>
						<th>{{ food_form.total_fat }} g</th>
					</tr>
					<tr>
						<th>Saturated Fat</th>
						<th>{{ food_form.saturated_fat }} g</th>
					</tr>
					<tr>
						<th>Cholesterol</th>
						<th>{{ food_form.cholesterol }} mg</th>
					</tr>
					<tr>
						<th>Sodium</th>
						<th>{{ food_form.sodium }} mg</th>
					</tr>
					<tr>
						<th>Total Carbohydrate</th>
						<th>{{ food_form.total_carbohydrate }} g</th>
					</tr>
					<tr>
						<th>Dietary Fibre</th>
						<th>{{ food_form.dietary_fibre }} g</th>
					</tr>
					<tr>
						<th>Sugar</th>
						<th>{{ food_form.sugar }} g</th>
					</tr>
					<tr>
						<th>Protein</th>
						<th>{{ food_form.protein }} g</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Save</button>
		</form>
	</body>
</html>

food_tracker/templates/add_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker - Add Meal</h1>
		<a href="{% url 'food:index' %}" class="btn btn-info">Back</a><br />
		<form role="form" action="" method="POST">
		    {% csrf_token %}
			<table class="table table-dark table-bordered table-striped">
				<tbody>
					<tr>
						<th>Food</th>
						<th>{{ meal_form.food }}</th>
					</tr>
					<tr>
						<th>Serving Size</th>
						<th>{{ meal_form.serving_size }}</th>
					</tr>
					<tr>
						<th>Meal Time</th>
						<th>{{ meal_form.meal_time }}</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Save</button>


		</form>
	</body>
</html>

food_tracker/templates/home.html
html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django People</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Django People</h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

food_tracker/templates/index.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker</h1>
		<a href="{% url 'auth_logout' %}">Logout</a> <br /><br />

		<a href="{% url 'auth_password_change' %}">Change Password</a> <br /><br />

		<a href="{% url 'food:add-meal' %}" class="btn btn-success">Add Meal</a> <br /> <br />

		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>Food</th>
					<th>Meal Time</th>
					<th>Calories</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for meal in meals %}
				<tr>
					<td>{{ meal.food }}</td>
					<td>{{ meal.get_meal_time_display }}</td>
					<td>{{ meal.get_calories }}</td>
					<td>
						<a href="" class="btn btn-info">View</a> 
					</td>
					<td>
						<a href="{% url 'food:update-meal' meal.id %}" class="btn btn-primary">Update</a> 
					</td>
					<td>
						<a href="{% url 'food:delete-meal' meal.id %}" class="btn btn-danger">Delete</a> 
					</td>
				</tr>
				{% empty %}
				<tr>
					<td colspan="6">No meals yet</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>

food_tracker/templates/list.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a href="{% url 'food:add-meal' %}" class="btn btn-success">Add Meal</a> <br /><br />
				</li>
				<li class="nav-item">
					<a href="{% url 'food:add-food' %}" class="btn btn-success">Add Food</a> <br /><br /> 
				</li>
			
			</ul>
			<button class="btn btn-outline-primary my-2 my-sm-0" type="submit"><a href = "{% url 'auth_password_change' %}">Change Password</a></button>
			<button class="btn btn-outline-primary my-2 my-sm-0" type="submit"><a href = "{% url 'auth_logout' %}">Log Out</a></button>
		</div>
		</nav>
		<h1 class = "font-italic">My Food Tracker</h1> <br /><br />
		
		<table class="table table-dark table-striped table-bordered">
			<thead>
				<tr>
					<th>Food</th>
					<th>Meal Time</th>
					<th>Total Calories</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for meal in meals %}
				<tr>
					<td>{{ meal.food.name }}</td>
					<td>{{ meal.get_meal_time_display }}</td>
					<td>{{ meal.get_calories }} kcal</td>
					<td>
						<a href="{% url 'food:view-meal' meal.id %}" class="btn btn-info">View</a>
					</td>
					<td>
						<a href="{% url 'food:update-meal' meal.id %}" class="btn btn-primary">Update</a>
					</td>
					<td>
						<a href="{% url 'food:delete-meal' meal.id %}" class="btn btn-danger">Delete</a>
					</td>
				</tr>
				{% empty %}
				<tr>
					<td colspan=6>No meals yet</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>

	</body>
</html>

food_tracker/templates/login.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        <style type="text/css">
            html,
            body {
                height: 100%;
            }

            body {
                padding-top: 40px;
                padding-bottom: 40px;
            }

            .form-signin {
                width: 100%;
                max-width: 330px;
                padding: 15px;
                margin: auto;
            }
        </style>

    </head>

    <body class="text-center">
        <form class="form-signin" method="POST" action="{% url 'auth_login' %}" role="form">
            {% csrf_token %}

            <h1>My Food Tracker</h1>

            {{ form.username.label }}
            {{ form.username }}

            {{ form.password.label }}
            {{ form.password }}

            <button class="btn btn-lg btn-primary" type="submit">Sign in</button>
            <input type="hidden" name="next" value="{% url 'food:index' %}" />
        </form>
    </body>
</html>

food_tracker/templates/password_change.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker</h1>
		<a href="{% url 'auth_logout' %}">Logout</a> <br /><br />

		{{ form.errors }}

		<form method="POST" action="{% url 'auth_password_change' %}">
		    {% csrf_token %}

		    {{ form.old_password.label }}
		    {{ form.old_password }} <br /><br />

		    {{ form.new_password1.label }}
		    {{ form.new_password1 }} <br /><br />
		    
		    {{ form.new_password2.label }}
		    {{ form.new_password2 }} <br /><br />

		    <button type="submit" class="btn btn-success">Change password</button>
		</form>
	</body>
</html>

food_tracker/templates/update_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker - Update Meal</h1>
		<form role="form" action="" method="POST">
		    {% csrf_token %}
			<table class="table table-bordered table-striped">
				<tbody>
					<tr>
						<th>Food</th>
						<th>{{ meal_form.food }}</th>
					</tr>
					<tr>
						<th>Serving Size</th>
						<th>{{ meal_form.serving_size }}</th>
					</tr>
					<tr>
						<th>Meal Time</th>
						<th>{{ meal_form.meal_time }}</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Save</button>
		</form>
	</body>
</html>

food_tracker/templates/view_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker - View Meal</h1>
		<a href="{% url 'food:index' %}" class="btn btn-info">Back</a><br />
		
		    {% csrf_token %}
			<table class="table table-dark table-bordered table-striped">
				<tbody>
					<tr>
						<th colspan = 2 style = "text-align:center">{{ meal.food }}</th>
					</tr>
					<tr>
						<th colspan = 2 style = "text-align:center">{{ meal.get_meal_time}}</th>
					</tr>
					<tr>
						<th>Calories</th>
						<th>{{ meal.get_calories }}</th>
					</tr>
					<tr>
						<th>Serving Size</th>
						<th>{{ meal.serving_size }}</th>
					</tr>
					<tr>
						<th>Total Fat</th>
						<th>{{ meal.get_total_fat }}</th>
					</tr>
					<tr>
						<th>Saturated Fat</th>
						<th>{{ meal.get_saturated_fat }}</th>
					</tr>
					<tr>
						<th>Cholesterol</th>
						<th>{{ meal.get_cholesterol }}</th>
					</tr>
					<tr>
						<th>Sodium</th>
						<th>{{ meal.get_sodium }}</th>
					</tr>
					<tr>
						<th>Total Carbohydrate</th>
						<th>{{ meal.get_total_carbohydrate }}</th>
					</tr>
					<tr>
						<th>Dietary Fibre</th>
						<th>{{ meal.get_dietary_fibre }}</th>
					</tr>
					<tr>
						<th>Sugar</th>
						<th>{{ meal.get_sugar }}</th>
					</tr>
					<tr>
						<th>Protein</th>
						<th>{{ meal.get_protein }}</th>
					</tr>
				</tbody>
			</table>
			<!-- <button type="submit" class="btn btn-success">Save</button> -->


		</form>
	</body>
</html>